### ISSUE TITLE
Allow the MVA to take a List of Variables from the Command Line

### ISSUE THREAD

**Issue by cow-co** [cow-co/FYP#17]
So we can easily specify how many and which variables we use.

**Comment by alexheslop1** [comment]
Current error of segmentation violation during TMVA build, after decorrelation transformation.

Error code:

Error in <TVectorT<double>::Use>: upb(-1) < lwb(0)

 *** Break *** segmentation violation

**Comment by alexheslop1** [comment]
Sorted
