### ISSUE TITLE
Allow More Than Two Plots on the Histogram Overlayer

### ISSUE THREAD

**Issue by cow-co** [cow-co/FYP#22]

**Comment by alexheslop1** [comment]
Do we ever need to plot more than 2 plots on one histogram? Only ever comparing signal vs background for each variable? I guess only other requirement is if we're comparing Chi2 between each track for different PT, could be useful to plot all of them

**Comment by cow-co** [comment]
Yeah the original purpose was to compare signal and background for low and high Q2 at the same time (i.e. 4 lots on the same graph) but that isn't really relevant any more so yeah I'll close this Issue.
