### ISSUE TITLE
Remove Title on Histograms

### ISSUE THREAD

**Issue by cow-co** [cow-co/FYP#31]
I think it looks more professional without.

For example, look at the plots around page 54 [here.](https://arxiv.org/pdf/1512.04442.pdf)

**Comment by cow-co** [comment]
make a `-v` parameter to the command-line input; if it is included, then read in title and axis name, if not then it does without them.

**Comment by alexheslop1** [comment]
Verbose options added, "-v" option as 9th argument input from command line, "-v" adds in title option rather than removes it
